[package]
name = "terraswap-helpers"
version = "0.1.0"
edition = "2021"
authors = ["Kerber0x <kerber0x@protonmail.com>"]
description = "Common helpers for other white whale"
license = "MIT"
repository = "https://github.com/White-Whale-DeFi-Platform/migaloo-core"
homepage = "https://whitewhale.finance"
documentation = "https://whitewhale.finance"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terraswap = { git = "https://github.com/terraswap/terraswap.git", tag = 'v2.7.0'}
cosmwasm-std = { version = "1.0.0" }
